### ISSUE TITLE
Training on my own voice wav files

### ISSUE THREAD

**Issue by ghost** [soroushmehr/sampleRNN_ICLR2017#10]
Is there a quick/dirty way to use my own wav files for training?
It seems to me that somehow I need to create the _train.npy, _valid.npy and _test.npy files.
thanks!

**Comment by ghost** [comment]
Just to add to my earlier question, the approach I would take is to use the MUSIC for the data_set option, but create my own mix of npy files, and change the code so although it will be executing the MUSIC (initial) code path, the __music_train_mean_std would actually have the values from __blizz_train_mean_std, as I'm assuming there was a reason for voice having a different set of values.

Would this general approach have a reasonable chance to work you think?

Thanks!

**Comment by kundan2510** [comment]
Yes, here is a step by step guide including preprocessing (start from Step 1):
https://github.com/soroushmehr/sampleRNN_ICLR2017/blob/master/datasets/music/preprocess.py

After following this, you'll use _2npy.py in the same folder.

(Entire preprocessing starting from downloading MUSIC dataset is at https://github.com/soroushmehr/sampleRNN_ICLR2017/blob/master/datasets/music/download_archive_preprocess.sh)

Let me know if you have questions related to it.

**Comment by ghost** [comment]
Thanks! What's the minimum size of the test & validation data do you think I should have? 

My impression is that the default MUSIC corpus had about 8% (each) compared to the training data, and the training data was about 560 minutes.

Since training runs are time consuming, I want to try stuff out with a smaller set first.

**Comment by kundan2510** [comment]
It's up to you. We usually keep each if them in 5-10% range.

**Comment by ghost** [comment]
I've ran into an issue in the preprocessing stage and I'm scratching my head and can't figure it out :(

_2npy.py is generating a training file that is too small, although i have plenty of data (for testing purpose, i'm just using the Beethoven Sonata 12,13,14 as the wav files to start with).

Here is what I see:
  94M all_music.npy
  63M  music_test.npy
   80  music_train.npy  <-- way too small
  32M  music_valid.npy <-- likely too big

If I dump out the array shapes from _2npy.py, i see this:
shape of np_arr (all_music) =  (383, 128000)
shape of train npy  =  (0, 128000) <-- this seems bad!
shape of valid npy  =  (127, 128000)
shape of test  npy  =  (256, 128000)

My general question is this ... is there an implicit assumption about data size? What's the context of the value 256 used to partition data into 3 npy files.

thanks!

**Comment by ghost** [comment]
So I've reasoned out that the value 256 (in file _2npy.py) should really be calculated value from the shape of the data, and maybe do something like this:
`np_arr_x` , np_arr_y = np.shape(np_arr)
`train_size_x` = int(np_arr_x * 0.8)
`test_size_x` = int(np_arr_x * 0.1)
`validation_size_x` = int(np_arr_x * 0.1)

After the above suggested udpate to _2npy.py, I now get reasonable size npy files, but have ran into a problem during traing phase which I'm digging into. Something to do with test_cost not being defined (two_tier.py, line 670).

**Comment by robinsloan** [comment]
I'm running into that same `test_cost` error -- really strange. I trained a model on the Beethoven music dataset for three days without a hitch.

Here's the full trace:

```
Training!
0 [Another epoch] 
Validation!
/home/robin/miniconda2/envs/samplernn/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
 Done!
Traceback (most recent call last):
  File "models/two_tier/two_tier.py", line 670, in <module>
    test_cost,
NameError: name 'test_cost' is not defined
```

My only intuition is that maybe the hard-coded `256` in the train/test/valid split that happens in `_2npy.py` is somehow important further down the line. (Like @LinkOne1A, I changed that value to accommodate a smaller dataset.)

Anyway, just wanted to let you know I'm muddling through this, too.

Thanks for a really interesting and impressive software package -- I was able to get the Beethoven model up and running seamlessly!

P.S. I've implemented a first pass at a general-purpose custom dataset loading script; you'll find `preprocess_custom_dataset.sh` along with a few supporting changes to other scripts here:

https://github.com/robinsloan/sampleRNN_ICLR2017/tree/master/datasets/music

Usability-wise, it's not quite ready for prime time (or a pull request), but it's working pretty well for me, present hiccup notwithstanding.

**Comment by ghost** [comment]
I'm still digging thru stuff as I try to use my own dataset. 

That said, I believe I solved the problem of `test_cost is not defined` problem by simply defining `test_cost=0.0` at the top of the file two_tier.py (the only model I'm using at this time) . I am newbie to python (but have decades of C/C++ industry expeience), anyhow, I find python strange, and this error leads me to think that (in python lang) the variable test_cost is defined on first assignemnt, but the error line (670) might be first referance. --- Then again, I may not know what I'm talking about since I really don't know python! <grin>! The fix does work.

**Comment by ghost** [comment]
So I'm not yet able to get a satisfactory training run. My feeling is that there is a minimum data size required to get good run, which is obvious, but so far it seems that about 22 minutes of audio data is insufficient.

I'm currently running a training set using a single wav file from the default/example/music training run, which was a succesful run, the file I used was download/BeethovenPianoSonata12.wav, from which the 8 second flac segments were generated and saved in downloads/parts.

Here is the shape and size info for the training runs:
shape of np_arr (all_music) =  (166, 128000)
shape of train_npy  =  (132, 128000)
shape of valid_npy  =  (16, 128000)
shape of test _npy  =  (16, 128000)

And the corresponding npy files:
  41M Mar 27 18:24 all_music.npy
 4.0M Mar 27 18:24 music_test.npy
  33M Mar 27 18:24 music_train.npy
 4.0M Mar 27 18:24 music_valid.npy

And here is the reason I don't think this training run is going well, notice how 'bad' some of the numbers are:
epoch:23	total iters:5751	wall clock time:3.22h
>>> Lowest valid cost:3.40282346639e+38	 Corresponding test cost:3.40282346639e+38
	train cost:0.3197	total time:1.69h	per iter:1.055s
	valid cost:nan	total time:0.00h
	test  cost:0.0000	total time:0.00h
Saving params! Done!
Train info saved! And plotted!
Sampling! 20 samples of 5 seconds length generated in 214.018519878 seconds. Done!
Validation Done!
Back to Training...
6000 [Another epoch] 
Validation! Done!

And here is the plot:
![train_log](https://cloud.githubusercontent.com/assets/26230594/24389747/e812838e-1338-11e7-8ff4-c9cbda03c4d2.png)

My plan is to abort this run, and try again with a larger subset of the Beethoven music files and see what I get.

**Comment by ghost** [comment]
Update: I am convinced now that significant amount of training data is necessary to have a reasonable training. 

One might say what does "significant" mean, good question, I only have a fuzzy answer for now.

## Run-A-1, a good run, duration of origianl musical data is huge = 9:38 hours (nine hours and 38 minutes)
This is the tier-2 test as mentioned in the readme.md file, it runs great, and produces reasonable wav segments. By reasonable, I mean some files have no noise bursts, and the sound seems like the piano and the music seems like something better than random.

## Run-A-2, seems to be a good run, duration of music data = 4:03 hours
This is same as Run-A-1, but with only BeethovenSonata wav files. I have only inspected cost numbers and they all look reasonble at epoch1, iter=2500

## Run-B-1, a bad run, duration of musical data = 22 minutes
Same as Run-1-A, but using the single wav file BeethovenPianoSonata12. See earlier comment re bad cost numbers)

## Run-B-2, a bad run, duration of musical data = 1:23 hours
Same as Run-1-A but a training run using a smaller subset from the same set of Beethoven wav files, where duration of the musical data is 1:23 hours. Results are unstable  (bad cost numbers, see my posting just above this one).

For comparison, and I do recognize there is a great deal of apples-vs-oranges going on here in my observations, but still, that said, I have a speech based training run (the original intent of this thread of discussion) where about 1/2 hour of total speech was used to train an implementaion of wavenet based on the model from https://github.com/ibab/tensorflow-wavenet. The training was stable and I was able to generate reasonable sounding speech: 
https://soundcloud.com/user-637335781/speech4-generated-from-a-40ksteps-training-using-vctk-corpus-wav48-for-single-user-p306 

I originally started this discussion with the intent to use about 30 minutes of speech to train sampleRNN, and ran into what seem to be unstable costs, which led the discussion to this final note. I suggest closing this thread in a day or two. I will start a new discussion when I have more data.

**Comment by robinsloan** [comment]
Here's one slightly weird idea for you, @LinkOne1A: how about augmenting a small dataset through duplication?

Usually, there's nothing inherently unworkable about training a neural network on just a few examples; it will just learn those examples _really well_ and overfit. Of course, I'm no expert -- maybe there's something different about `sampleRNN`'s architecture. But I suspect the differences you're encountering have something to do with the data pipeline, not the model itself. 

So, if you're not fed up at this point, it might be interesting to take the same dataset you used in your `Run-B-1` or `Run-B-2`, duplicate the `wav` parts (filenames don't matter, as long as they end with `flac`) 3 or 4 times, and try again. My prediction: good runs! But if they do indeed end up bad again, that would certainly be interesting…

**Comment by kundan2510** [comment]
Data augmentation with duplication is not a good idea. You can think training through multiple epochs as training on same data multiple times.

What can help you in case of smaller data is to reduce the model size, add different kind of regularization like dropout, etc.

However, the performance of neural network greatly depends on the amount of data with variability it it. For better performance, there is no better alternative than using larger amount of data if you can afford.

**Comment by robinsloan** [comment]
@kundan2510 You're right, of course, but I tend to think if it's a matter of getting the network to train successfully and produce interesting results, a little incorrectness and inefficiency is OK! And particularly at the enthusiast level, where cracking open the model architecture and modifying it can be a real challenge.

This is a terrific code release, by the way -- really impressively polished and easy to get started with. Thanks!

**Comment by kundan2510** [comment]
Thanks @robinsloan. My point is: augmentation by duplication is not going to help at all. When you train for multiple epochs, you anyway use same data point many times. BTW, if you want to reduce model size, you need to change this option `--dim DIM             Dimension of RNN and MLPs`. Making `--dim 512` will reduce model size by nearly 1/4th which can help you get better results on smaller datasets. You can play with different values of it depending on your dataset. This will also help speed-up the model.

**Comment by robinsloan** [comment]
@kundan2510 Oh, that's good advice on model size -- I forgot there were all those great command-line options! 👍👍

**Comment by ghost** [comment]
I think we are done for now with this discussion, so I'm closing it. Thanks for the replied.
