### ISSUE TITLE
What were the parameters for the mu-law-1 posting at soundcloud?

### ISSUE THREAD

**Issue by ghost** [soroushmehr/sampleRNN_ICLR2017#12]
Hello; 
Specifically : https://soundcloud.com/samplernn/samplernn-blizzard-mu-law-1?in=samplernn/sets/mu-law

The sound quality is excellent, very little white noise, or clicks, none-really!
Thanks!

**Comment by kundan2510** [comment]
It would be something like:
`THEANO_FLAGS=mode=FAST_RUN,device=gpu0,floatX=float32 python -u models/two_tier/two_tier.py --exp BEST_2TIER --n_frames 64 --frame_size 16 --emb_size 256 --skip_conn False --dim 1024 --n_rnn 3 --rnn_type GRU --q_levels 256 --q_type mu-law --batch_size 64 --weight_norm True --learn_h0 True --which_set MUSIC`

Please note the change of parameter `--q_type mu-law`. I think you can play around with other parameters like `--dim` or `--n_rnn` depending on the compute and memory you have, results should not change much.

**Comment by ghost** [comment]
Thanks, and about how many iteration, epochs?
Also, since I don't have access to the BLIZZARD DB, what was the audio duration in total? A rough estimate would be fine/thanks!

**Comment by soroushmehr** [comment]
Roughly 10 epochs. We used 20.5 hours for our experiments. However, the original dataset is much larger.

**Comment by ghost** [comment]
ok, thanks!
