### ISSUE TITLE
Want a PowerPoint file to understand the motivation, idea

### ISSUE THREAD

**Issue by OneDirection9** [soroushmehr/sampleRNN_ICLR2017#23]
Dear, I have read the paper and code to understand the idea. But there are still some points that I can not understand. So I create this issue to look for a ppt to understand the idea.

Thanks!

**Comment by soroushmehr** [comment]
Following presentations might help:
1.  By Yoshua Bengio: https://www.youtube.com/watch?v=vEAq_sBf1CA&t=15m23s
2.  By Aaron Courville: https://www.youtube.com/watch?v=AzqLZPHQONM
