### ISSUE TITLE
Trying to train using a new dataset, test_cost undefined

### ISSUE THREAD

**Issue by vonpost** [soroushmehr/sampleRNN_ICLR2017#4]
I'm trying to train a model using a different dataset than the Beethoven sonatas, and I'm having a bit of trouble when running 

`$ python -u models/three_tier/three_tier.py --exp BEST_3TIER --seq_len 512 --big_frame_size 8 --frame_size 2 --emb_size 256 --skip_conn False --dim 1024 --n_rnn 1 --rnn_type GRU --q_levels 256 --q_type linear --batch_size 128 --weight_norm True --learn_h0 True --which_set MUSIC`

Basically after the first batch has been fully iterated through I get an issue with test_cost being undefined. I've tried with the two tier model as well, but it looks like the code is the same in both models, that is:

```
        if valid_cost < lowest_valid_cost:
            lowest_valid_cost = valid_cost
            print "\n>>> Best validation cost of {} reached. Testing!"\
                    .format(valid_cost),
            test_cost, test_time = monitor(test_feeder)
```

The first time test_cost is defined is in the code above, however if the conditional isn't true we're still going to try to use test_cost on line 860 (in three tier) like this (and I believe further on in the code, after hacking it a bit, that we try to use it again):

```
        print_info = print_info.format(epoch,
                                       total_iters,
                                       (time()-exp_start)/3600,
                                       ....

                                       test_cost,
                                       test_time/3600)
```
Which means we're calling an undefined test_cost. I'm not quite sure of the role of test_cost in the first batch so I cannot really modify the code to get it working.

**Comment by mattearnshaw** [comment]
@vonpost how did you solve this? i guess initializing `test_cost` to 0 should be sufficient, but this issue should be reopened
