### ISSUE TITLE
Wavenet parameters

### ISSUE THREAD

**Issue by weixsong** [soroushmehr/sampleRNN_ICLR2017#6]
Hi,

As you mentioned in your paper, you have re-implemented WaveNet, could you share with me some parameters that you used?

such as:
1. how many the skip channels you use?
2. how many the dilation channels?
3. Is the skip channel values of each Convolution layer are summed together directly without weights?

Thanks very much.

**Comment by kundan2510** [comment]
You can see all hyper-parameters here:https://github.com/soroushmehr/sampleRNN_ICLR2017/blob/master/models/one_tier/wavent.py#L8
Specifically, we use skip_channels = 64, dilation_channel = 64, we learn the weights of each contribution.
