### ISSUE TITLE
SampleRNN (2-tier) example (from readme.md) won't run

### ISSUE THREAD

**Issue by ghost** [soroushmehr/sampleRNN_ICLR2017#8]
Interesting paper and approach, it would be very exciting to compare results with wavenet, however, an attempted test run suggested in readme.md (mentioned as sampleRNN(2-tier) fails with the following error:

MemoryError: Error allocating 2147483648 bytes of device memory (CNMEM_STATUS_OUT_OF_MEMORY).

I am familiar with TensorFlow (of Google) but not Theano, so I have not looked at the code yet, I'm hoping it might be something easy for you guys to spot and direct me to a quick soltuion.

The GPU I have is GeForce GTX 1080, 8Gig of mem. The initial CNMeM is set to 50% in the .theanorc file ( [lib]
cnmem=0.5): 
     Using gpu device 0: GeForce GTX 1080 
     (CNMeM is enabled with initial size: 50.0% of memory, cuDNN 5110)

During initial run, the nvidia-smi tool shows initial alloc of GPU mem at ~4Gig, it stays at that level and the training run fails moments later with the above mem alloc issue.

The training run is inside a docker image, with the following pertinent version info:
nvcc --version
    Cuda compilation tools, release 8.0, V8.0.61
Python:
	sys.version_info	sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
Numpy:
	.__version__	1.11.0
Theano:
	.__version__	0.9.0rc2.dev-19540d4e3064fe0dc0e1281f517bad0f355e46a2
pip show lasagne
    Metadata-Version: 2.0
    Name: Lasagne
    Version: 0.1

Thanks!

**Comment by kundan2510** [comment]
Your error suggests that you are not giving enough memory for the model to run successfully.
Running wavenet requires a lot of GPU memory, please either reduce batch-size or set cnmem=0.95 to increase memory available to the model.

**Comment by ghost** [comment]
Well, same issue when cnmem=0.95:
Reboot machine, set cnmem=0.95, run test, resulst:
Using gpu device 0: GeForce GTX 1080 (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 5110)
MemoryError: Error allocating 2147483648 bytes of device memory (CNMEM_STATUS_OUT_OF_MEMORY).

**Comment by kundan2510** [comment]
Can you write the exact command that you write for launching the experiment?

**Comment by ghost** [comment]
yes, from the readme.md : 
THEANO_FLAGS=mode=FAST_RUN,THEANORC=/root/.theanorc,device=gpu0,floatX=float32 python -u models/two_tier/two_tier.py --exp BEST_2TIER --n_frames 64 --frame_size 16 --emb_size 256 --skip_conn False --dim 1024 --n_rnn 3 --rnn_type GRU --q_levels 256 --q_type linear --batch_size 128 --weight_norm True --learn_h0 True --which_set MUSIC

And the rc file has the following - $ more /root/.theanorc
[global]
device=gpu
floatX=float32
optimizer_including=cudnn
[lib]
cnmem=0.99
[nvcc]
fastmath=True

**Comment by kundan2510** [comment]
Please try this:
`THEANO_FLAGS=mode=FAST_RUN,THEANORC=/root/.theanorc,device=gpu0,floatX=float32 python -u models/two_tier/two_tier.py --exp BEST_2TIER --n_frames 64 --frame_size 16 --emb_size 256 --skip_conn False --dim 1024 --n_rnn 3 --rnn_type GRU --q_levels 256 --q_type linear --batch_size 8 --weight_norm True --learn_h0 True --which_set MUSIC`

Let me know if this does not work.

**Comment by ghost** [comment]
Sure, copy/pasted from your reply, but I get (what seems like a) parser/argument error:
...
Using gpu device 0: GeForce GTX 1080 (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 5110)
usage: two_tier.py [-h] [--exp EXP] --n_frames N_FRAMES --frame_size
                   FRAME_SIZE --weight_norm WEIGHT_NORM --emb_size EMB_SIZE
                   --skip_conn SKIP_CONN --dim DIM --n_rnn {1,2,3,4,5}
                   --rnn_type {LSTM,GRU} --learn_h0 LEARN_H0 --q_levels
                   Q_LEVELS --q_type {linear,a-law,mu-law} --which_set
                   {ONOM,BLIZZ,MUSIC} --batch_size {64,128,256} [--debug]
                   [--resume]
two_tier.py: error: argument --batch_size: invalid choice: 8 (choose from 64, 128, 256)

So I try again by settting --batch_size=64, which seems the min in the above suggested error, and I'm waiting to see what happens...

**Comment by kundan2510** [comment]
Let us know how it goes.

**Comment by ghost** [comment]
Thanks for your help!

This seems to be running fine so far... here is the status:

Total parameter count for this cost:
	39243264
Wall clock time spent before training started: 0.02h
Training!
0 500 1000 1500 2000 2500 3000 3500 4000 4500 5000 
Validation! Done!

>>> Best validation cost of 1.33546721935 reached. Testing! Done!
>>> test cost:1.29125571251	total time:120.902484894
epoch:0	total iters:5123	wall clock time:1.59h
>>> Lowest valid cost:1.33546721935	 Corresponding test cost:1.29125571251
	train cost:1.5596	total time:1.50h	per iter:1.054s
	valid cost:1.3355	total time:0.03h
	test  cost:1.2913	total time:0.03h
Saving params! Done!
Train info saved! And plotted!
Sampling! 20 samples of 5 seconds length generated in 213.851065874 seconds. Done!
Validation Done!
Back to Training...

**Comment by kundan2510** [comment]
Great, it works.
