### ISSUE TITLE
Example of music generated using mostly default parameters (tier-2), at epoch9 and epoch11

### ISSUE THREAD

**Issue by ghost** [soroushmehr/sampleRNN_ICLR2017#9]
In case folks are interested, I've uploaded several of the generated wav files at epoch=9 and epoch=11.

Please browse to:  https://soundcloud.com/user-637335781

Thanks to kundan2510 for answering my earlier question re mem alloc error and to reduce batch size.

The trainnig run was as follows:
`THEANO_FLAGS=mode=FAST_RUN,device=gpu0,floatX=float32 python -u models/two_tier/two_tier.py --exp BEST_2TIER --n_frames 64 --frame_size 16 --emb_size 256 --skip_conn False --dim 1024 --n_rnn 3 --rnn_type GRU --q_levels 256 --q_type linear --batch_size 64 --weight_norm True --learn_h0 True --which_set MUSIC`

GPU: Single GPU : 8 GB GTX 1080 with 2560 CUDA Cores

Epoch 9 took about 24 hours, and getting to epoch 11 took an additional 6 hours. Training run was aborted at the start of epoch12

This is a very exciting project/code you guys have! wow!

-Best regards!

**Comment by kundan2510** [comment]
I am glad that it worked. Closing the issue.
